[versions]
slf4j = "2.0.13"
grpc = "1.73.0"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.0.2" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-services = { module = "io.grpc:grpc-services", version.ref = "grpc" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }

[bundles]
grpc = [
    "grpc-stub",
    "grpc-protobuf",
    "grpc-services",
    "grpc-netty-shaded",
]